# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_no', models.IntegerField()),
                ('tagname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(unique=True)),
                ('local', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=40)),
                ('place_type', models.IntegerField()),
                ('address', models.TextField()),
                ('comment', models.TextField()),
                ('tags', models.ManyToManyField(to='traveler.Tag')),
            ],
        ),
    ]
